### PR TITLE
Modernize the script

### PR DESCRIPTION
**Pull request by rguilmont**
- Use poetry for dependency management
- Fix a bug where a lot of PromQL queries where modified and invalid afterwards
- Logs with colors, for readability
- Add a basic test scenario for PromQL transformation functions
- Actually use real environment variables, if set
- Support https on remote grafana ( by default ) but allow to change the protocol

### CODE REVIEW

**Comment by yotamloe** [comment]
@rguilmont Thanks a lot for your contribution!
We will review it soon and keep you updated

**Review by yotamloe — APPROVED** [review]
LGTM.
Lovely addition to this project. I tested the tool with the addition and looked like it's working fine. I updated the usage documentation.

**Comment by yotamloe** [comment]
@rguilmont Thanks again!
This PR will be merged after we will review and change our official docs regarding this project.

**Comment by rguilmont** [comment]
Thanks a lot ! Very happy i could help :) For the sake of coherence; i can apply the same style of updates to the metrics extractor tools. Would you be interested ?

**Pull request merged**
